name: Run ESLint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリをクローン
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # 必要なNode.jsのバージョンを指定

      # 3. 依存関係をインストール
      - name: Install dependencies
        run:  |
          cd react-template
          npm install --no-package-lock

      # 4. ESLint を実行
      - name: Run ESLint
        run:  |
          cd react-template
          npx eslint .
